project:
  type: website
  render:
    - "index.qmd"
    - "!docs"

website:
  title: "Visualizing the AI Economy"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

authors:
  - name: Ellie Parker
  - name: Mengyao Chen
  - name: Tom Dobbs
  - name: Rob Puncel 
