project:
  type: website
  render:
    - "*.qmd"
    - "!docs"

website:
  title: "Visualizing the AI Economy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exploratory-report.qmd
        text: Exploratory Report
      - href: midterm-presentation.qmd
        text: Midterm Presentation
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

authors:
  - name: Ellie Parker
  - name: Mengyao Chen
  - name: Tom Dobbs
  - name: Rob Puncel 